[26438]  wireguard bridge consider mis http != 200 corrections

diff --git a/docker/wireguard/run b/docker/wireguard/run
--- a/docker/wireguard/run
+++ b/docker/wireguard/run
@@ -28,8 +28,9 @@ echo "$(date): Public Key: ${PUBLIC_KEY}"
 ### Upate MIS information
 CALL_STATUS=$(curl -s -w "%{http_code}" --header "X-Redmine-API-Key:${MIS_APIKEY}" --header 'Content-Type: application/json' --location --request GET "${MIS_URL}/projects/${MIS_PROJECTID}/issues.json?subject=myelexis-bridge&tracker_id=15&limit=1" -o curl_response_body)
 if [ $CALL_STATUS != "200" ]; then
-    echo "$(date): MIS - Issue query (project-id $MIS_PROJECTID) returned HTTP Status Code $CALL_STATUS - check MIS settings. Exiting."
-    exit -1
+    echo "$(date): MIS - Query error: Project $MIS_PROJECTID, HTTP $CALL_STATUS. Check settings. Sleeping 20s, then exiting."
+    sleep 20
+    exit 1
 fi
 
 MIS_ISSUE_JSON=$(cat curl_response_body)
