[17927] Implement myElexis-bridge support

diff --git a/ee-cli/ee-cli b/ee-cli/ee-cli
--- a/ee-cli/ee-cli
+++ b/ee-cli/ee-cli
@@ -1,15 +1,16 @@
 #!/usr/bin/env bash
 
-ROOT_DIR=`dirname "$(perl -e 'use Cwd "abs_path"; print abs_path(shift)' $0)"`
-CLI_ENTRYPOINT=`basename $0`
+ROOT_DIR=$(dirname "$(perl -e 'use Cwd "abs_path"; print abs_path(shift)' $0)")
+CLI_ENTRYPOINT=$(basename $0)
 
 . "$ROOT_DIR/utils"
 
 export $(egrep -v '^#' $ROOT_DIR/../.env | xargs)
 export INSTALL_DIR=${ROOT_DIR}/../
+export DOCKER_DIR=${INSTALL_DIR}/docker/compose/
 export SITE_DIR=${INSTALL_DIR}site/
 
-ee_util () {
+ee_util() {
     tput setaf 8
     docker pull -q medevit/eenv-config
     docker build -q -t ee-util ${INSTALL_DIR}docker/ee-util/.
@@ -29,7 +30,7 @@ while [[ -d "$CMD_FILE" && $CMD_ARG_START -le $# ]]; do
     if [[ "${!CMD_ARG_START}" == "help" ]]; then
         # Strip off the "help" portion of the command
         ARGS=("$@")
-        unset "ARGS[$((CMD_ARG_START-1))]"
+        unset "ARGS[$((CMD_ARG_START - 1))]"
         ARGS=("${ARGS[@]}")
 
         "$ROOT_DIR/help" $0 ${ARGS[@]}
@@ -37,7 +38,7 @@ while [[ -d "$CMD_FILE" && $CMD_ARG_START -le $# ]]; do
     fi
 
     CMD_FILE="$CMD_FILE/${!CMD_ARG_START}"
-    CMD_ARG_START=$(($CMD_ARG_START+1))
+    CMD_ARG_START=$(($CMD_ARG_START + 1))
 done
 
 # Place the arguments for the command in their own list
@@ -55,9 +56,9 @@ fi
 # If we didn't couldn't find the exact command the user entered then warn them
 # about it, and try to be helpful by displaying help for that directory.
 if [[ ! -f "$CMD_FILE" ]]; then
-    "$ROOT_DIR/help" $0 ${@:1:$(($CMD_ARG_START-1))}
-    >&2 echo -e "\033[31mWe could not find the command \033[36m$CLI_ENTRYPOINT ${@:1:$CMD_ARG_START}\033[39m"
-    >&2 echo -e "To help out, we've shown you the help docs for \033[36m$CLI_ENTRYPOINT ${@:1:$(($CMD_ARG_START-1))}\033[39m"
+    "$ROOT_DIR/help" $0 ${@:1:$(($CMD_ARG_START - 1))}
+    echo >&2 -e "\033[31mWe could not find the command \033[36m$CLI_ENTRYPOINT ${@:1:$CMD_ARG_START}\033[39m"
+    echo >&2 -e "To help out, we've shown you the help docs for \033[36m$CLI_ENTRYPOINT ${@:1:$(($CMD_ARG_START - 1))}\033[39m"
     exit 3
 fi
 
@@ -74,7 +75,7 @@ for arg in "${CMD_ARGS[@]}"; do
         "$ROOT_DIR/help" $0 ${@:1:$((CMD_ARG_START - 1))} ${CMD_ARGS[@]}
         exit 3
     fi
-    arg_i=$((arg_i+1))
+    arg_i=$((arg_i + 1))
 done
 
 # Run the command and capture its exit code for introspection
